# Site settings
title: veronica michelle art and design
email: contact@veronicamichelle.com
description: > # this means to ignore newlines until "baseurl:"
  art and design portfolio
baseurl:  # the subpath of your site, e.g. /blog/
url:  veronicamichelle.com # the base hostname & protocol for your site
twitter_username: bitcoinwarlock

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  work:
    output: true
    permalink: /work/:path/

